[package]
name = "soviet-sim"
version = "1.0.0"
authors = ["loovjo <jonathan.loov@gmail.com>"]

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true

[dependencies]
lazy_static = "1.0.0"
textwrap = "0.10.0"
